# Base16 Nova - alacritty color config
# George Essig (https:&#x2F;&#x2F;github.com&#x2F;gessig), Trevor D. Miller (https:&#x2F;&#x2F;trevordmiller.com)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x3c4c55'
foreground = '0xc5d4dd'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x3c4c55'
cursor = '0xc5d4dd'

# Normal colors
[colors.normal]
black = '0x3c4c55'
red = '0x83afe5'
green = '0x7fc1ca'
yellow = '0xa8ce93'
blue = '0x83afe5'
magenta = '0x9a93e1'
cyan = '0xf2c38f'
white = '0xc5d4dd'

# Bright colors
[colors.bright]
black = '0x899ba6'
red = '0x7fc1ca'
green = '0x556873'
yellow = '0x6a7d89'
blue = '0x899ba6'
magenta = '0x899ba6'
cyan = '0xf2c38f'
white = '0x556873'
