# Base16 pinky - alacritty color config
# Benjamin (https:&#x2F;&#x2F;github.com&#x2F;b3nj5m1n)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x171517'
foreground = '0xf5f5f5'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x171517'
cursor = '0xf5f5f5'

# Normal colors
[colors.normal]
black = '0x171517'
red = '0xffa600'
green = '0xff0066'
yellow = '0x20df6c'
blue = '0x00ffff'
magenta = '0x007fff'
cyan = '0x6600ff'
white = '0xf5f5f5'

# Bright colors
[colors.bright]
black = '0x383338'
red = '0x00ff66'
green = '0x1b181b'
yellow = '0x1d1b1d'
blue = '0xe7dbdb'
magenta = '0xffffff'
cyan = '0xdf206c'
white = '0xf7f3f7'
