# Base16 Edge Light - alacritty color config
# cjayross (https:&#x2F;&#x2F;github.com&#x2F;cjayross)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xfafafa'
foreground = '0x5e646f'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfafafa'
cursor = '0x5e646f'

# Normal colors
[colors.normal]
black = '0xfafafa'
red = '0xdb7070'
green = '0x7c9f4b'
yellow = '0xd69822'
blue = '0x6587bf'
magenta = '0xb870ce'
cyan = '0x509c93'
white = '0x5e646f'

# Bright colors
[colors.bright]
black = '0x5e646f'
red = '0xdb7070'
green = '0x7c9f4b'
yellow = '0xd69822'
blue = '0x6587bf'
magenta = '0xb870ce'
cyan = '0x509c93'
white = '0x5e646f'
