# Base16 Sparky - alacritty color config
# Leila Sother (https:&#x2F;&#x2F;github.com&#x2F;mixcoac)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x072b31'
foreground = '0xf4f5f0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x072b31'
cursor = '0xf4f5f0'

# Normal colors
[colors.normal]
black = '0x072b31'
red = '0xff585d'
green = '0x78d64b'
yellow = '0xfbdd40'
blue = '0x4698cb'
magenta = '0xd59ed7'
cyan = '0x2dccd3'
white = '0xf4f5f0'

# Bright colors
[colors.bright]
black = '0x003b49'
red = '0xff8f1c'
green = '0x00313c'
yellow = '0x003c46'
blue = '0x00778b'
magenta = '0xf5f5f1'
cyan = '0x9b704d'
white = '0xffffff'
