# Base16 Green Screen - alacritty color config
# Chris Kempson (http:&#x2F;&#x2F;chriskempson.com)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x001100'
foreground = '0x00bb00'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x001100'
cursor = '0x00bb00'

# Normal colors
[colors.normal]
black = '0x001100'
red = '0x007700'
green = '0x00bb00'
yellow = '0x007700'
blue = '0x009900'
magenta = '0x00bb00'
cyan = '0x005500'
white = '0x00bb00'

# Bright colors
[colors.bright]
black = '0x007700'
red = '0x009900'
green = '0x003300'
yellow = '0x005500'
blue = '0x009900'
magenta = '0x00dd00'
cyan = '0x005500'
white = '0x00ff00'
