# Base16 Windows NT Light - alacritty color config
# Fergus Collins (https:&#x2F;&#x2F;github.com&#x2F;C-Fergus)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x808080'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x808080'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0x800000'
green = '0x008000'
yellow = '0x808000'
blue = '0x000080'
magenta = '0x800080'
cyan = '0x008080'
white = '0x808080'

# Bright colors
[colors.bright]
black = '0xc0c0c0'
red = '0xffff00'
green = '0xeaeaea'
yellow = '0xd5d5d5'
blue = '0xa0a0a0'
magenta = '0x404040'
cyan = '0x00ff00'
white = '0x000000'
