# Base16 Circus - alacritty color config
# Stephan Boyer (https:&#x2F;&#x2F;github.com&#x2F;stepchowfun) and Esther Wang (https:&#x2F;&#x2F;github.com&#x2F;ewang12)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x191919'
foreground = '0xa7a7a7'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x191919'
cursor = '0xa7a7a7'

# Normal colors
[colors.normal]
black = '0x191919'
red = '0xdc657d'
green = '0x84b97c'
yellow = '0xc3ba63'
blue = '0x639ee4'
magenta = '0xb888e2'
cyan = '0x4bb1a7'
white = '0xa7a7a7'

# Bright colors
[colors.bright]
black = '0x5f5a60'
red = '0x4bb1a7'
green = '0x202020'
yellow = '0x303030'
blue = '0x505050'
magenta = '0x808080'
cyan = '0xb888e2'
white = '0xffffff'
