# Base16 Railscasts - alacritty color config
# Ryan Bates (http:&#x2F;&#x2F;railscasts.com)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x2b2b2b'
foreground = '0xe6e1dc'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x2b2b2b'
cursor = '0xe6e1dc'

# Normal colors
[colors.normal]
black = '0x2b2b2b'
red = '0xda4939'
green = '0xa5c261'
yellow = '0xffc66d'
blue = '0x6d9cbe'
magenta = '0xb6b3eb'
cyan = '0x519f50'
white = '0xe6e1dc'

# Bright colors
[colors.bright]
black = '0x5a647e'
red = '0xcc7833'
green = '0x272935'
yellow = '0x3a4055'
blue = '0xd4cfc9'
magenta = '0xf4f1ed'
cyan = '0xbc9458'
white = '0xf9f7f3'
