# Base16 Measured Light - alacritty color config
# Measured (https:&#x2F;&#x2F;measured.co)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xfdf9f5'
foreground = '0x292929'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xfdf9f5'
cursor = '0x292929'

# Normal colors
[colors.normal]
black = '0xfdf9f5'
red = '0xac1f35'
green = '0x0c680c'
yellow = '0x645a00'
blue = '0x0158ad'
magenta = '0x6645c2'
cyan = '0x01716f'
white = '0x292929'

# Bright colors
[colors.bright]
black = '0x5a5a5a'
red = '0xad5601'
green = '0xf9f5f1'
yellow = '0xffeada'
blue = '0x404040'
magenta = '0x181818'
cyan = '0xa81a66'
white = '0x000000'
