# Base16 PaperColor Dark - alacritty color config
# Jon Leopard (http:&#x2F;&#x2F;github.com&#x2F;jonleopard) based on PaperColor Theme (https:&#x2F;&#x2F;github.com&#x2F;NLKNguyen&#x2F;papercolor-theme)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1c1c1c'
foreground = '0x808080'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1c1c1c'
cursor = '0x808080'

# Normal colors
[colors.normal]
black = '0x1c1c1c'
red = '0x585858'
green = '0xaf87d7'
yellow = '0xafd700'
blue = '0xff5faf'
magenta = '0x00afaf'
cyan = '0xffaf00'
white = '0x808080'

# Bright colors
[colors.bright]
black = '0xd7af5f'
red = '0x5faf5f'
green = '0xaf005f'
yellow = '0x5faf00'
blue = '0x5fafd7'
magenta = '0xd7875f'
cyan = '0x5f8787'
white = '0xd0d0d0'
