# Base16 PaperColor Light - alacritty color config
# Jon Leopard (http:&#x2F;&#x2F;github.com&#x2F;jonleopard) based on PaperColor Theme (https:&#x2F;&#x2F;github.com&#x2F;NLKNguyen&#x2F;papercolor-theme)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xeeeeee'
foreground = '0x444444'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xeeeeee'
cursor = '0x444444'

# Normal colors
[colors.normal]
black = '0xeeeeee'
red = '0xbcbcbc'
green = '0x8700af'
yellow = '0xd70087'
blue = '0xd75f00'
magenta = '0x005faf'
cyan = '0xd75f00'
white = '0x444444'

# Bright colors
[colors.bright]
black = '0x5f8700'
red = '0xd70000'
green = '0xaf0000'
yellow = '0x008700'
blue = '0x0087af'
magenta = '0x005f87'
cyan = '0x005f87'
white = '0x878787'
