# Base16 Twilight - alacritty color config
# David Hart (https:&#x2F;&#x2F;github.com&#x2F;hartbit)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1e1e1e'
foreground = '0xa7a7a7'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1e1e1e'
cursor = '0xa7a7a7'

# Normal colors
[colors.normal]
black = '0x1e1e1e'
red = '0xcf6a4c'
green = '0x8f9d6a'
yellow = '0xf9ee98'
blue = '0x7587a6'
magenta = '0x9b859d'
cyan = '0xafc4db'
white = '0xa7a7a7'

# Bright colors
[colors.bright]
black = '0x5f5a60'
red = '0xcda869'
green = '0x323537'
yellow = '0x464b50'
blue = '0x838184'
magenta = '0xc3c3c3'
cyan = '0x9b703f'
white = '0xffffff'
