# Base16 Embers Light - alacritty color config
# Jannik Siebert (https:&#x2F;&#x2F;github.com&#x2F;janniks)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0xd1d6db'
foreground = '0x323b43'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xd1d6db'
cursor = '0x323b43'

# Normal colors
[colors.normal]
black = '0xd1d6db'
red = '0x576d82'
green = '0x6d8257'
yellow = '0x57826d'
blue = '0x82576d'
magenta = '0x6d5782'
cyan = '0x826d57'
white = '0x323b43'

# Bright colors
[colors.bright]
black = '0x75808a'
red = '0x578282'
green = '0xaeb6be'
yellow = '0x909aa3'
blue = '0x47505a'
magenta = '0x20262c'
cyan = '0x575782'
white = '0x0f1316'
