# Base16 Rosé Pine Moon - alacritty color config
# Emilia Dunfelt &lt;edun@dunfelt.se&gt;

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x232136'
foreground = '0xe0def4'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x232136'
cursor = '0xe0def4'

# Normal colors
[colors.normal]
black = '0x232136'
red = '0xeb6f92'
green = '0x3e8fb0'
yellow = '0xea9a97'
blue = '0xc4a7e7'
magenta = '0xf6c177'
cyan = '0x9ccfd8'
white = '0xe0def4'

# Bright colors
[colors.bright]
black = '0x6e6a86'
red = '0xf6c177'
green = '0x2a273f'
yellow = '0x393552'
blue = '0x908caa'
magenta = '0xe0def4'
cyan = '0x56526e'
white = '0x56526e'
