# Base16 Vesper - alacritty color config
# FormalSnake (https:&#x2F;&#x2F;github.com&#x2F;formalsnake)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x101010'
foreground = '0xb7b7b7'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x101010'
cursor = '0xb7b7b7'

# Normal colors
[colors.normal]
black = '0x101010'
red = '0xde6e6e'
green = '0x5f8787'
yellow = '0xffc799'
blue = '0x8eaaaa'
magenta = '0xd69094'
cyan = '0x60a592'
white = '0xb7b7b7'

# Bright colors
[colors.bright]
black = '0x333333'
red = '0xdab083'
green = '0x232323'
yellow = '0x222222'
blue = '0x999999'
magenta = '0xc1c1c1'
cyan = '0x876c4f'
white = '0xd5d5d5'
