# Base16 moe-pink-dark - alacritty color config
# uwidev

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x26292E'
foreground = '0xBDC3C7'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x26292E'
cursor = '0x0xBDC3C7'

# Normal colors
[colors.normal]
black = '0x101010'
red = '0xFF4488'
green = '0x2BB1AF'
yellow = '0xFFE185'
blue = '0x4488cc'
magenta = '0xC679DD'
cyan = '0x39ABDC'
white = '0x7F8C8D'

# Bright colors
[colors.bright]
black = '0x333333'
red = '0xFF44BB'
green = '0x25A09D'
yellow = '0xEED077'
blue = '0x4488ff'
magenta = '0xB870CF'
cyan = '0x369ECD'
white = '0x9CACA8'
