# Base16 Brogrammer - alacritty color config
# Vik Ramanujam (http:&#x2F;&#x2F;github.com&#x2F;piggyslasher)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x1f1f1f'
foreground = '0x4e5ab7'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x1f1f1f'
cursor = '0x4e5ab7'

# Normal colors
[colors.normal]
black = '0x1f1f1f'
red = '0xd6dbe5'
green = '0xf3bd09'
yellow = '0x1dd361'
blue = '0x5350b9'
magenta = '0x0f7ddb'
cyan = '0x1081d6'
white = '0x4e5ab7'

# Bright colors
[colors.bright]
black = '0xecba0f'
red = '0xde352e'
green = '0xf81118'
yellow = '0x2dc55e'
blue = '0x2a84d2'
magenta = '0x1081d6'
cyan = '0xffffff'
white = '0xd6dbe5'
